version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10

    working_directory: ~/repo

    steps:
       - setup_remote_docker:
            docker_layer_caching: true

       - checkout

        # build and push Docker image
       - run: |
           TAG=0.1.$CIRCLE_BUILD_NUM

           docker-compose build --parallel
           docker tag apiance_apiance-client:latest $DOCKER_USER/apiance-client:$TAG
           docker tag apiance_apiance-server:latest $DOCKER_USER/apiance-server:$TAG

           echo "$DOCKER_USER"

           docker login -u "$DOCKER_USER" -p "$DOCKER_PASS"
           docker push $DOCKER_USER/apiance-client:$TAG
           docker push $DOCKER_USER/apiance-server:$TAG
